runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /(.*\.(js|css|svg|png|jpg|gif|scss|eot|woff|ttf|woff2)(|\.map))$
    static_files: clientApp/\1
    upload: clientApp/(.*)(|\.map)
  - url: /.*
    static_files: clientApp/index.html
    upload: clientApp/.*

  - url: /(.+\.js)
    static_files: dist/clientApp/\1
    upload: dist/clientApp/(.+\.js)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.css)
    static_files: dist/clientApp/\1
    upload: dist/clientApp/(.+\.css)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.png)
    static_files: dist/clientApp/\1
    upload: dist/clientApp/(.+\.png)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.jpg)
    static_files: dist/clientApp/\1
    upload: dist/clientApp/(.+\.jpg)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.gif)
    static_files: dist/clientApp/\1
    upload: dist/clientApp/(.+\.gif)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.svg)
    static_files: dist/clientApp/\1
    upload: dist/clientApp/(.+\.svg)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.eot)
    static_files: dist/clientApp/\1
    upload: dist/clientApp/(.+\.eot)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.ttf)
    static_files: dist/clientApp/\1
    upload: dist/clientApp/(.+\.ttf)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.woff2)
    static_files: dist/clientApp/\1
    upload: dist/clientApp/(.+\.woff2)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.woff)
    static_files: dist/clientApp/\1
    upload: dist/clientApp/(.+\.woff)
    secure: always
    redirect_http_response_code: 301

  - url: /favicon.ico
    static_files: dist/clientApp/favicon.ico
    upload: dist/clientApp/favicon.ico
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.json)
    static_files: dist/clientApp/\1
    upload: dist/clientApp/(.+\.json)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+)
    static_files: dist/clientApp/index.html
    upload: dist/clientApp/index.html
    secure: always
    redirect_http_response_code: 301

  - url: /
    static_files: dist/clientApp/index.html
    upload: dist/clientApp/index.html
    secure: always
    redirect_http_response_code: 301

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE    
  - (?!^clientApp)  